using System.IO;

#if UNITY_EDITOR
using UnityEditor;
#endif
using UnityEngine;
using UnityEngine.SceneManagement;

namespace LUTBeam
{
    #if UNITY_EDITOR
    [System.Serializable]
    public class GoboArray
    {
        public string name = "gobo";
        public Texture[] gobos;
    }
    #endif
    
    public class LUTBeamManager : MonoBehaviour
    {
#if UNITY_EDITOR
        // Forces unity to not copy the last element when adding a new one
        private void OnValidate()
        {
            if (goboArray.Length > lastGoboArraySize && lastGoboArraySize != -1)
            {
                goboArray[goboArray.Length - 1].name = "New Gobo Array";
                goboArray[goboArray.Length - 1].gobos = null;
            }

            lastGoboArraySize = goboArray.Length;
        }

        [SerializeField, HideInInspector]
        private int lastGoboArraySize = -1;

        public GoboArray[] goboArray;
        public TextureFormat format = TextureFormat.BC4;

        public string AutoGenerateDirectory = "Assets/LUTBeam/Autogenerated";

        public int LUTResolution = 1024;
        public int GoboResolution = 512;

        bool IsPowerOfTwo(int x)
        {
            return (x & (x - 1)) == 0;
        }

        void SetProgress(float progress, string message)
        {
            EditorUtility.DisplayProgressBar("LUT Beams", message, progress);
        }

        [ContextMenu("Generate Texture Array")]
        public void _GenerateTextureArray()
        {
            SetProgress(0, "Setup");

            if (!IsPowerOfTwo(GoboResolution))
                return;

            if (!IsPowerOfTwo(LUTResolution))
                return;

            // calculate mip count.
            // lowest resolution BC4 supports is 4x4 so stop there.

            int goboMipCount = 0;
            int GoboRes = GoboResolution;
            while (GoboRes > 4) { GoboRes /= 2; goboMipCount++; }

            int lutMipCount = 0;
            int LUTRes = LUTResolution;
            while (LUTRes > 4) { LUTRes /= 2; lutMipCount++; }

            for (int i = 0; i < goboArray.Length; i++)
            {
                Texture[] gobos = goboArray[i].gobos;
                string prefix = goboArray[i].name;

                if (gobos.Length == 0)
                    continue;

                Texture2D[][] goboTextures = new Texture2D[gobos.Length][];
                Texture2D[][] goboTexturesExtraBlur = new Texture2D[gobos.Length][];
                Texture2D[][] lutTextures = new Texture2D[gobos.Length][];

                Material material = new Material(Shader.Find("LUTBeam/GoboLookupGenerator"));

                for (int q = 0; q < gobos.Length; q++)
                {
                    SetProgress(q / (float)gobos.Length, "Generating " + (q + 1) + "/" + gobos.Length + " - Setup...");

                    if (!(gobos[q] is Texture2D))
                        continue;

                    // load the texture from disk instead so it's not compressed.
                    Texture2D InputGobo = new Texture2D(2, 2);
                    string path = AssetDatabase.GetAssetPath(gobos[q]);
                    byte[] bytes = File.ReadAllBytes(path);
                    ImageConversion.LoadImage(InputGobo, bytes, false);

                    if (!InputGobo)
                        return;

                    goboTextures[q] = new Texture2D[goboMipCount];
                    goboTexturesExtraBlur[q] = new Texture2D[goboMipCount];
                    lutTextures[q] = new Texture2D[lutMipCount];

                    SetProgress(q / (float)gobos.Length, "Generating " + (q + 1) + "/" + gobos.Length + " - Blurring...");
                    for (int mip = 0; mip < goboMipCount; mip++)
                    {
                        int res = Mathf.Max(1, GoboResolution >> mip);
                        RenderTexture tempRTGobo = new RenderTexture(res, res, 32, RenderTextureFormat.ARGBFloat);

                        material.SetTexture("_MainTex", mip == 0 ? InputGobo : goboTextures[q][mip - 1]);
                        Shader.SetGlobalFloat("_MipLevel", mip);
                        Shader.SetGlobalFloat("_EnableBake_Gobo", 1);
                        Shader.SetGlobalFloat("_BlurStrength", 0.01f);
                        Graphics.Blit(null, tempRTGobo, material);
                        Shader.SetGlobalFloat("_EnableBake_Gobo", 0);
                        Shader.SetGlobalFloat("_MipLevel", 0);

                        RenderTexture.active = tempRTGobo;
                        Texture2D texGobo = new Texture2D(res, res, TextureFormat.RGBAFloat, false);
                        texGobo.ReadPixels(new Rect(0, 0, res, res), 0, 0);
                        texGobo.Apply();
                        RenderTexture.active = null;

                        goboTextures[q][mip] = texGobo;
                    }

                    SetProgress(q / (float)gobos.Length, "Generating " + (q + 1) + "/" + gobos.Length + " - Blurring (again)...");
                    for (int mip = 0; mip < goboMipCount; mip++)
                    {
                        int res = Mathf.Max(1, GoboResolution >> mip);
                        RenderTexture tempRTGobo = new RenderTexture(res, res, 32, RenderTextureFormat.ARGBFloat);

                        material.SetTexture("_MainTex", mip == 0 ? InputGobo : goboTexturesExtraBlur[q][mip - 1]);
                        Shader.SetGlobalFloat("_MipLevel", mip);
                        Shader.SetGlobalFloat("_EnableBake_Gobo", 1);
                        Shader.SetGlobalFloat("_BlurStrength", 0.03f);
                        Graphics.Blit(null, tempRTGobo, material);
                        Shader.SetGlobalFloat("_EnableBake_Gobo", 0);
                        Shader.SetGlobalFloat("_MipLevel", 0);

                        RenderTexture.active = tempRTGobo;
                        Texture2D texGobo = new Texture2D(res, res, TextureFormat.RGBAFloat, false);
                        texGobo.ReadPixels(new Rect(0, 0, res, res), 0, 0);
                        texGobo.Apply();
                        RenderTexture.active = null;

                        goboTexturesExtraBlur[q][mip] = texGobo;
                    }

                    SetProgress(q / (float)gobos.Length, "Generating " + (q + 1) + "/" + gobos.Length + " - Raymarching...");
                    // Generate the whole LUT mip chain, mip 0 first
                    for (int mip = 0; mip < lutMipCount; mip++)
                    {
                        int res = Mathf.Max(1, LUTResolution >> mip);
                        RenderTexture tempRTLut = new RenderTexture(res, res, 32, RenderTextureFormat.ARGBFloat);

                        // give the volumetrics extra blurred ones.
                        material.SetTexture("_MainTex", goboTexturesExtraBlur[q][Mathf.Min(goboMipCount-1, mip)]);
                        Shader.SetGlobalFloat("_MipLevel", mip);

                        // Enable supersampling mode of the baker because it makes it look way better!
                        Shader.SetGlobalFloat("_EnableBake_Supersample", 1);
                        Graphics.Blit(null, tempRTLut, material);
                        Shader.SetGlobalFloat("_EnableBake_Supersample", 0);
                        Shader.SetGlobalFloat("_MipLevel", 0);

                        RenderTexture.active = tempRTLut;
                        Texture2D texLut = new Texture2D(res, res, TextureFormat.RGBAFloat, false);
                        texLut.ReadPixels(new Rect(0, 0, res, res), 0, 0);
                        texLut.Apply();
                        RenderTexture.active = null;

                        lutTextures[q][mip] = texLut;
                    }

                    SetProgress(q / (float)gobos.Length, "Generating " + (q + 1) + "/" + gobos.Length + " - Converting to SRGB...");
                    // Convert linear to srgb in the texture
                    for (int mip = 0; mip < goboMipCount; mip++)
                    {
                        Texture2D texGobo = goboTextures[q][mip];
                        var data = texGobo.GetRawTextureData<float>();
                        for (int j = 0; j < data.Length; j++)
                        {
                            data[j] = Mathf.LinearToGammaSpace(data[j]);
                        }
                        texGobo.Apply(false, false);
                    }

                    SetProgress(q / (float)gobos.Length, "Generating " + (q + 1) + "/" + gobos.Length + " - Converting to SRGB (again)...");
                    // Convert linear to srgb in the texture
                    for (int mip = 0; mip < lutMipCount; mip++)
                    {
                        Texture2D texLut = lutTextures[q][mip];
                        var data = texLut.GetRawTextureData<float>();
                        for (int j = 0; j < data.Length; j++)
                        {
                            data[j] = Mathf.LinearToGammaSpace(data[j]);
                        }
                        texLut.Apply(false, false);
                    }
                    SetProgress(q / (float)gobos.Length, "Generating " + (q + 1) + "/" + gobos.Length + " - Done...");
                }

                Scene scene = SceneManager.GetActiveScene();

                if (!Directory.Exists(AutoGenerateDirectory))
                    Directory.CreateDirectory(AutoGenerateDirectory);

                Texture2DArray texArray = new Texture2DArray(GoboResolution, GoboResolution, gobos.Length, format, goboMipCount, false);
                Texture2DArray lutArray = new Texture2DArray(LUTResolution, LUTResolution, gobos.Length, format, lutMipCount, false);

                SetProgress(0.25f, "Copying");
                for (int j = 0; j < gobos.Length; j++)
                {
                    //SetProgress((float)i / (float)gobos.Length);
                    for (int mip = 0; mip < goboMipCount; mip++)
                    {
                        EditorUtility.CompressTexture(goboTextures[j][mip], format, TextureCompressionQuality.Best);
                        Graphics.CopyTexture(goboTextures[j][mip], 0, 0, texArray, j, mip);
                    }

                    for (int mip = 0; mip < lutMipCount; mip++)
                    {
                        EditorUtility.CompressTexture(lutTextures[j][mip], format, TextureCompressionQuality.Best);
                        Graphics.CopyTexture(lutTextures[j][mip], 0, 0, lutArray, j, mip);
                    }
                }

                SetProgress(0.5f, "Creating");

                string texArrayFilePath = $"{AutoGenerateDirectory}/{scene.name} - Gobo Textures.asset";
                string lutArrayFilePath = $"{AutoGenerateDirectory}/{scene.name} - LUT Textures.asset";
                if (!string.IsNullOrWhiteSpace(prefix))
                {
                    texArrayFilePath = $"{AutoGenerateDirectory}/{scene.name} {prefix} - Gobo Textures.asset";
                    lutArrayFilePath = $"{AutoGenerateDirectory}/{scene.name} {prefix} - LUT Textures.asset";
                }


                Texture2DArray existingTexArray = AssetDatabase.LoadAssetAtPath<Texture2DArray>(texArrayFilePath);
                if (existingTexArray)
                {
                    EditorUtility.CopySerialized(texArray, existingTexArray);
                    EditorUtility.SetDirty(existingTexArray);
                    texArray = existingTexArray;
                }
                else
                {
                    AssetDatabase.CreateAsset(texArray, texArrayFilePath);
                }

                Texture2DArray existingLutArray = AssetDatabase.LoadAssetAtPath<Texture2DArray>(lutArrayFilePath);
                if (existingLutArray)
                {
                    EditorUtility.CopySerialized(lutArray, existingLutArray);
                    EditorUtility.SetDirty(existingLutArray);
                    lutArray = existingLutArray;
                }
                else
                {
                    AssetDatabase.CreateAsset(lutArray, lutArrayFilePath);
                }

                SetProgress(0.8f, "Saving");
                AssetDatabase.SaveAssets();

                EditorGUIUtility.PingObject(lutArray);
            }

            EditorUtility.ClearProgressBar();
        }
#endif
    }
}
